name: manheim
favicon: null
layout_spectrum: 0.4919815759640187
typography_spectrum: 0.9036206118762493
title: Test Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0175a6'
    - '#6b78af'
    - '#1b2433'
    - '#b4c0cf'
    - '#906957'
  brandStrength: 0.75
  lightness: 0.4572633558418602
  saturation: 0.739372770069167
  rhythmicContrast: 0.5372674851678312
purpose: []
